version: "3"
services:

  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=projectdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=654321
      - MYSQL_HOST=db
    ports:
      - "8585:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.3
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - MYSQL_USER=root
      - MYSQL_PASSWORD=654321
      - MYSQL_DATABASE=projectdb
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: { driver: local }